# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure('2') do |config|
  config.vm.synced_folder '../', '/build'

  config.vm.define :stretch do |stretch|
    stretch.vm.box = 'generic/debian9'
    stretch.vm.provision :shell, name: 'install tools', path: '../script/shell/installer'
  end
end
